/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import Foundation;
#import "AVTAvatar.h"

@interface AVTAnimoji: AVTAvatar
+ (id)_scenePathForPuppetNamed:(id)arg1;
+ (id)puppetNamed:(id)arg1 options:(id)arg2;
+ (id)animojiNamed:(id)arg1;
@end
